apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-manager-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-events
roleRef:
  kind: ClusterRole
  name: argo-workflow-manager
  apiGroup: rbac.authorization.k8s.io
