apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-manager
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-manager-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: argo-workflow-manager
  apiGroup: rbac.authorization.k8s.io
