apiVersion: v1
kind: Service
metadata:
  name: argo-nodeport
  namespace: argo
spec:
  ports:
  - name: http
    port: 2746
    targetPort: 2746
    protocol: TCP
    nodePort: 30770

  selector:
    app: argo-server
  type: NodePort