apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  gitlab:
    example:
      projects:
        - "yourgitusername/yourgitrepo" # Replace with your repo name
        - "777"
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://3e57-45-144-6-2.ngrok-free.app
        headers:
          - name: Authorization
            valueFrom:
              secretKeyRef:
                name: argo-token
                key: token
      events:
        - PushEvents
      accessToken:
        key: token
        name: gitlab-access-token
      enableSSLVerification: false
      # Gitlab Base url. Use your gitlab hostname
      gitlabBaseURL: https://gitlab.com
      deleteHookOnFinish: true
