apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tee-task-scheduling-
  namespace: argo
spec:
  entrypoint: kata-example
  templates:
  - name: kata-example
    steps:
    - - name: task-1-local
        template: task-1-local

  - name: task-1-local
    container:
      image: alpine:latest
      command: [echo]
      args: ["{{workflow.name}}"]