apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: argo
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
    nodePort: 30771
  - name: https
    port: 9001
    targetPort: 9001
    protocol: TCP
    nodePort: 30772
  selector:
    app: minio
  type: NodePort